version: "3.8"
services:
  backend:
    build: ./api
    container_name: backend_container
    ports:
      - "4002:4001"
    volumes:
      - /Users/aqibjavaid/Documents/Docker/app/api:/app
      - /Users/aqibjavaid/Documents/Docker/app/api/node_modules

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3002:3000"
    volumes:
      - /Users/aqibjavaid/Documents/Docker/app/frontend:/app
      - /Users/aqibjavaid/Documents/Docker/app/frontend/node_modules
