export default [
  {
    _id: "63a1e01a89d578165eaa40a6",
    index: 0,
    guid: "fbc8a71a-f7e8-4547-86a0-987285d654a0",
    isActive: true,
    balance: "$1,087.73",
    picture: "http://placehold.it/32x32",
    age: 26,
    eyeColor: "green",
    name: "Hahn Byers",
    gender: "male",
    company: "CINESANCT",
    email: "hahnbyers@cinesanct.com",
    phone: "+1 (894) 513-3111",
    address: "875 Hudson Avenue, Fostoria, Hawaii, 3370",
    about:
      "Do nisi enim labore est sint quis excepteur eiusmod ullamco laborum est. Eiusmod aute nisi sunt mollit minim sit fugiat. Irure tempor dolor proident sit nulla magna nostrud ut.\r\n",
    registered: "2014-12-01T01:01:35 -05:00",
    latitude: 15.621496,
    longitude: -113.537023,
    tags: [
      "incididunt",
      "ipsum",
      "pariatur",
      "incididunt",
      "occaecat",
      "nostrud",
      "sit",
    ],
    friends: [
      {
        id: 0,
        name: "Nash Delacruz",
      },
      {
        id: 1,
        name: "Blake Burns",
      },
      {
        id: 2,
        name: "Kimberley Willis",
      },
    ],
    greeting: "Hello, Hahn Byers! You have 7 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "63a1e01a07dc7f27569aded0",
    index: 1,
    guid: "9ddfa12d-c6f6-4af5-a35d-2923c0a3b88b",
    isActive: false,
    balance: "$3,285.00",
    picture: "http://placehold.it/32x32",
    age: 30,
    eyeColor: "brown",
    name: "Jayne Kidd",
    gender: "female",
    company: "CINASTER",
    email: "jaynekidd@cinaster.com",
    phone: "+1 (936) 534-3012",
    address: "655 Woodruff Avenue, Richmond, Puerto Rico, 4057",
    about:
      "Laboris dolore dolor tempor anim excepteur adipisicing ut non anim officia in dolore. Consectetur dolore quis est veniam. Adipisicing consequat sunt fugiat cillum aute sunt nulla quis adipisicing qui mollit ex sit. Dolor consequat do aliqua exercitation reprehenderit exercitation eiusmod sint do magna sint est.\r\n",
    registered: "2015-01-21T10:57:55 -05:00",
    latitude: -26.722976,
    longitude: -134.796823,
    tags: [
      "culpa",
      "proident",
      "magna",
      "cupidatat",
      "reprehenderit",
      "officia",
      "adipisicing",
    ],
    friends: [
      {
        id: 0,
        name: "Fannie Powell",
      },
      {
        id: 1,
        name: "Delores Frank",
      },
      {
        id: 2,
        name: "Donovan Davenport",
      },
    ],
    greeting: "Hello, Jayne Kidd! You have 2 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "63a1e01a024e211da5c9925b",
    index: 2,
    guid: "13ef77dd-aac4-4dd4-bb8f-e337ee02ec10",
    isActive: false,
    balance: "$1,835.53",
    picture: "http://placehold.it/32x32",
    age: 34,
    eyeColor: "brown",
    name: "Noemi Hammond",
    gender: "female",
    company: "GEEKOSIS",
    email: "noemihammond@geekosis.com",
    phone: "+1 (985) 577-2920",
    address: "214 Taylor Street, Lawrence, California, 8489",
    about:
      "In ipsum non consectetur Lorem ea sunt ea eu. Ullamco nisi cupidatat qui dolor voluptate proident aute esse non occaecat sit aliquip. Duis ullamco aute aliquip dolor qui consequat ad id dolor sunt quis laboris amet. Fugiat cupidatat ullamco ea nisi magna nulla commodo eiusmod sunt officia magna nisi ea. Eu ut minim commodo excepteur dolor reprehenderit mollit non. Tempor nisi anim laborum dolore pariatur velit exercitation.\r\n",
    registered: "2014-05-22T11:46:38 -05:00",
    latitude: 7.702144,
    longitude: 96.248271,
    tags: ["ullamco", "dolore", "aute", "mollit", "nisi", "sint", "dolore"],
    friends: [
      {
        id: 0,
        name: "Carole Wise",
      },
      {
        id: 1,
        name: "Lena Keller",
      },
      {
        id: 2,
        name: "Adriana Roman",
      },
    ],
    greeting: "Hello, Noemi Hammond! You have 3 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "63a1e01a77f7d550e6d05743",
    index: 3,
    guid: "b9f7f7b6-2c93-449e-b3d8-f738e0c8e935",
    isActive: false,
    balance: "$2,333.25",
    picture: "http://placehold.it/32x32",
    age: 25,
    eyeColor: "green",
    name: "Leona Norman",
    gender: "female",
    company: "CODACT",
    email: "leonanorman@codact.com",
    phone: "+1 (868) 505-3862",
    address: "258 Cortelyou Road, Gorst, Rhode Island, 1209",
    about:
      "Ad duis occaecat laboris fugiat amet veniam. Lorem sint reprehenderit voluptate quis non velit eu minim occaecat exercitation nulla commodo. Sit exercitation fugiat proident excepteur veniam dolor nulla occaecat reprehenderit. In cupidatat amet cillum Lorem et pariatur in proident amet minim deserunt culpa. Quis commodo qui eiusmod exercitation. Laborum laboris sint est voluptate anim do minim non dolor pariatur cillum sunt commodo laboris.\r\n",
    registered: "2018-02-14T01:14:41 -05:00",
    latitude: -44.076492,
    longitude: 23.651274,
    tags: [
      "voluptate",
      "exercitation",
      "dolor",
      "excepteur",
      "quis",
      "labore",
      "qui",
    ],
    friends: [
      {
        id: 0,
        name: "Pitts Chapman",
      },
      {
        id: 1,
        name: "Hyde Holden",
      },
      {
        id: 2,
        name: "Sherri Saunders",
      },
    ],
    greeting: "Hello, Leona Norman! You have 3 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "63a1e01a61e79d3d25d6f64a",
    index: 4,
    guid: "494884cf-40c3-4c57-9131-1ad3d9f042a0",
    isActive: false,
    balance: "$2,797.73",
    picture: "http://placehold.it/32x32",
    age: 21,
    eyeColor: "green",
    name: "Faulkner Gray",
    gender: "male",
    company: "OBONES",
    email: "faulknergray@obones.com",
    phone: "+1 (845) 553-3154",
    address: "574 Macdougal Street, Fairview, South Carolina, 3265",
    about:
      "Nulla est fugiat sunt ad. Nostrud cillum quis esse sit tempor amet sunt labore anim velit irure officia incididunt sit. Sit qui mollit enim anim magna adipisicing aliqua eu voluptate laborum. Ullamco aliquip aliquip sit occaecat minim Lorem eiusmod proident nostrud consequat. Adipisicing nostrud eiusmod eu eu irure do incididunt consequat reprehenderit mollit eiusmod fugiat do. Pariatur sit ex aliquip sunt ad velit eiusmod aliquip minim proident ex cupidatat.\r\n",
    registered: "2016-01-02T02:16:58 -05:00",
    latitude: -54.090174,
    longitude: 19.967416,
    tags: ["culpa", "cillum", "eu", "esse", "ea", "nostrud", "occaecat"],
    friends: [
      {
        id: 0,
        name: "Sellers Montoya",
      },
      {
        id: 1,
        name: "Francis Bishop",
      },
      {
        id: 2,
        name: "Tami Lawrence",
      },
    ],
    greeting: "Hello, Faulkner Gray! You have 6 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "63a1e01a5d2b36972f95577e",
    index: 5,
    guid: "d1a208f6-d87f-4f1b-8e05-2915973a5405",
    isActive: false,
    balance: "$1,456.20",
    picture: "http://placehold.it/32x32",
    age: 30,
    eyeColor: "brown",
    name: "Earlene Hickman",
    gender: "female",
    company: "ECLIPTO",
    email: "earlenehickman@eclipto.com",
    phone: "+1 (877) 408-2100",
    address: "817 Linwood Street, Nettie, Connecticut, 3883",
    about:
      "Laborum sunt nostrud quis laboris aliquip aute. Nisi ullamco ad proident ex. Ullamco minim officia cupidatat id reprehenderit ut dolor. Laboris duis sint sint eu. Sint labore irure dolor eiusmod adipisicing et.\r\n",
    registered: "2020-01-10T08:36:27 -05:00",
    latitude: -40.189372,
    longitude: 92.048314,
    tags: ["deserunt", "quis", "velit", "duis", "et", "sit", "mollit"],
    friends: [
      {
        id: 0,
        name: "Simon Landry",
      },
      {
        id: 1,
        name: "Rush Chaney",
      },
      {
        id: 2,
        name: "Diann Benton",
      },
    ],
    greeting: "Hello, Earlene Hickman! You have 4 unread messages.",
    favoriteFruit: "banana",
  },
];
